TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: -0.4
  max_vel_theta: 6.2830
  min_vel_theta: -6.2830
  min_in_place_vel_theta: 0.31415
  escape_vel: -0.2
  
  acc_lim_theta: 50.0
  acc_lim_x: 5.0
  ##acc_lim_y: 10.0
  
  holonomic_robot: false
  controller_frequency: 50.0
  
  sim_time: 1.5
  meter_scoring: true
  dwa: false