map_type: costmap
obstacle_range: 4.0
raytrace_range: 4.0
robot_radius: 0.20
transform_tolerance: 0.21
inflation_radius: 0.21

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: scan, marking: true, clearing: true}